### ISSUE TITLE
Integrating with ArduPilot

### ISSUE THREAD

**Issue by ChinmayDSastry** [heron/heron_simulator#15]
Hi, is it possible to integrate the heron ship with ArduPilot in Gazebo with mavros without commanding it through SITL?

Thank You

**Comment by civerachb-cpr** [comment]
This may be possible, but is not a use-case we have investigated.  Please feel free to try it out and let us know if it works!

If you have to make any changes to Heron repositories to make it work properly with ArduPilot you're welcome to submit a PR for our review.
