### ISSUE TITLE
FR: Noetic Release

### ISSUE THREAD

**Issue by onurbagoren** [heron/heron_simulator#18]
Is there any plan to port the simulator to ROS Noetic? 

I am specifically thinking of the use of RViz in Noetic in order to interact with the Heron, as I am unable to find a resource besides `ros-kinetic-heron-rviz` that allows using RViz with the robot.

Thank you!

**Comment by civerachb-cpr** [comment]
Hi, thanks for your question.

Melodic packages for Heron can be installed by adding the Clearpath apt and rosdep sources (see http://packages.clearpathrobotics.com) on Ubuntu 18.04 and running `sudo apt-get install ros-melodic-heron-*`.  (You'll also need to set up the general ROS sources following the instructions found at http://wiki.ros.org/melodic/Installation/Ubuntu)

All the source code for Heron is available here on github: https://github.com/heron.  Note that the MCU firmware is closed-source, and can only be installed through apt by adding the Clearpath deb sources.

At this point we do not have plans to upgrade the Heron past ROS Melodic.  This unfortunately means we will not be releasing pre-compiled Noetic packages, nor will Heron be upgraded to ROS2.  If you need Noetic tools for your Heron you will need to build the relevant packages from source.  Note that Noetic drops support for Python2, so many packages will require updates to their Python scripts to upgrade them to Python3.

**Comment by onurbagoren** [comment]
Thank you, the explanation and the links really help!
