### ISSUE TITLE
Undefined Symbol Error

### ISSUE THREAD

**Issue by onurbagoren** [heron/heron_simulator#19]
- OS: Ubuntu 20.04 and 18.04
 - ROS Distro: Noetic and Melodic
 - Built from source or installed: Built from source
 - Commit hash: a086c053d5defe8ad286616549f8af943833d73a

 **Expected behaviour**
I am attempting to add a camera to the Heron as an additional sensor. I added the following snippet of code to `heron/heron_description/urdf/sensors.xacro`:
```
  <!-- Add a camera link -->
  <link name="$(arg suffix_ns)camera_link" />
  <joint name="$(arg suffix_ns)camera_joint" type="fixed">
    <origin xyz="$(optenv HERON_CAMERA_XYZ 0.0 0.0 0.0)" rpy="$(optenv HERON_CAMERA_RPY 0.0 0.0 0.0)" />
    <parent link="$(arg suffix_ns)base_link" />
    <child link="$(arg suffix_ns)camera_link" />
  </joint>
  
  <!-- Mount a camera -->
  <gazebo>
    <plugin name="camera_controller" filename="libuuv_gazebo_ros_camera_plugin.so">
      <updateRate>30</updateRate>
      <robotNamespace>/$(arg namespace)</robotNamespace>
      <bodyName>$(arg suffix_ns)base_link</bodyName>
      <frameName>$(arg suffix_ns)camera_link</frameName>
      <topicName>/$(arg suffix_ns)camera/image_raw</topicName>
      <cameraName>$(arg suffix_ns)camera</cameraName>
      <cameraSrvName>$(arg suffix_ns)camera/camera_info</cameraSrvName>
      <cameraInfoTopicName>/$(arg suffix_ns)camera/camera_info</cameraInfoTopicName>
      <cameraInfoSrvName>$(arg suffix_ns)camera/camera_info</cameraInfoSrvName>
      <cameraInfoFile>$(find heron_description)/urdf/sensors/camera_info.yaml</cameraInfoFile>
      <cameraInfoFrame>$(arg suffix_ns)camera_link</cameraInfoFrame>
      <cameraFov>$(optenv HERON_CAMERA_FOV 90)</cameraFov>
      <cameraPitch>$(optenv HERON_CAMERA_PITCH 0)</cameraPitch>
      <cameraYaw>$(optenv HERON_CAMERA_YAW 0)</cameraYaw>
      <cameraRoll>$(optenv HERON_CAMERA_ROLL 0)</cameraRoll>
      <cameraX>$(optenv HERON_CAMERA_X 0)</cameraX>
      <cameraY>$(optenv HERON_CAMERA_Y 0)</cameraY>
      <cameraZ>$(optenv HERON_CAMERA_Z 0)</cameraZ>
      <cameraZOffset>$(optenv HERON_CAMERA_Z_OFFSET 0)</cameraZOffset>
      <cameraYawOffset>$(optenv HERON_CAMERA_YAW_OFFSET 0)</cameraYawOffset>
    </plugin>
  </gazebo>
```

This uses the UUV Camera plugin, so in order to reproduce the error, the [UUV Simulator](https://github.com/uuvsimulator/uuv_simulator) is also required

 **Actual behaviour**
I ran into issues with undefined symbol from the `gazebo::DepthCameraPlugin.hh` shared library. 
The error is as follows:
`[Err] [Plugin.hh:212] Failed to load plugin libuuv_gazebo_ros_camera_plugin.so: /home/$USER/Simulators/uuv_simulator/devel/lib/libuuv_gazebo_ros_camera_plugin.so: undefined symbol: _ZTIN6gazebo17DepthCameraPluginE
`
There were earlier errors relating to this from two undefined functions from that shared library: `void OnNewReflectanceFrame` and `void OnNewNormalsFrame`. I wrote empty functions for them so I wouldn't get the undefined symbol error.
But this error, upon digging into it further with ldd, seems to point to the constructor of the constructor of the library `public: DepthCameraPlugin();`. This happened in both the Noetic and Melodic distros that I am testing with.

**To Reproduce**
Provide the steps to reproduce:
- Paste the snippet of code provided in the beginning of the Issue description to `heron/heron_description/urdf/sensors.xacro`.
- In the `uuv_simulator` sensor plugins, add the following functions to `UnderwaterCameraROSPlugin.hh`:
```
    /// \brief Update the reflectance frame
    public: virtual void OnNewReflectanceFrame(const float *_reflectance,
                              unsigned int _width, unsigned int _height,
                              unsigned int _depth, const std::string &_format);

    /// \brief Update the normals frame
    public: virtual void OnNewNormalsFrame(const float *_normals,
                              unsigned int _width, unsigned int _height,
                              unsigned int _depth, const std::string &_format);
```
- In the `uuv_simulator` sensor plugins, add the following functions to `UnderwaterCameraROSPlugin.cc`:
```
/////////////////////////////////////////////////
void UnderwaterCameraROSPlugin::OnNewReflectanceFrame(const float *_reflectance,
  unsigned int _width, unsigned int _height,
  unsigned int _depth, const std::string &_format)
{

}

/////////////////////////////////////////////////
void UnderwaterCameraROSPlugin::OnNewNormalsFrame(const float *_normals,
  unsigned int _width, unsigned int _height,
  unsigned int _depth, const std::string &_format)
{
  
}
```
- Run `catkin_make` and source the environment
- On one terminal, launch a UUV world (i.e `roslaunch uuv_gazebo_worlds mangalia.launch`
- On a separate terminal, launch the heron with `roslaunch heron_gazebo spawn_heron.launch`
- The error appears on the first terminal, where the world was launched

**Other notes**
I am looking for both recommendations on how to include a camera to the Heron, and how I would go about doing that. This has been my process so far, but if there are any faults or anything I am missing, please do let me know!
I am also looking for advice on how to resolve this Undefined Symbol error as well. Thank you!

**Comment by civerachb-cpr** [comment]
This appears to be a bug with the UUV plugins, not with Heron.  I'd advise you file a bug-report with them to address the missing symbol issue.

To add a simple RGB camera to the Heron, I just tested this method on Ubuntu 18.04 with ROS Melodic and it worked

```
<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <!-- Add a camera link -->
  <link name="camera_link" />
  <joint name="camera_joint" type="fixed">
    <origin xyz="$(optenv HERON_CAMERA_XYZ 0.0 0.0 0.15)" rpy="$(optenv HERON_CAMERA_RPY 0.0 0.0 0.0)" />
    <parent link="base_link" />
    <child link="camera_link" />
  </joint>

  <!-- Mount a camera -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera">
      <update_rate>30.0</update_rate>
      <camera name="camera">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>
</robot>
```

Save this file somewhere on your computer.  Then set the HERON_URDF_EXTRAS envar to point to it:

```bash
export HERON_URDF_EXTRAS=/path/to/the/file/above.urdf.xacro
```

Then start your simulation, e.g.:
```
roslaunch heron_gazebo heron_lake_world.launch
```

Check that you have the topic `/camera/image_raw` in `rostopic list`.  Using `rostopic hz` should show it publishing at about 30Hz using the above configuration.  You can add this topic to Rviz' visualization as well.

Lake world screenshots:
![heron_camera_gazebo](https://user-images.githubusercontent.com/59611394/141381124-bdb9c937-903d-4dd7-b480-dd53bc229755.png)
![heron_camera_rviz](https://user-images.githubusercontent.com/59611394/141381127-2ac7954f-49ef-4e15-a3e1-80f25db42c5b.png)

Inspection world screenshots
![heron-inspection-gazebo](https://user-images.githubusercontent.com/59611394/141381497-260a3471-8abc-4c8b-b05c-5f6a322bc55f.png)
![heron-inspection-rviz](https://user-images.githubusercontent.com/59611394/141381498-803c9f48-5c3f-4b86-9e73-ffd3b1b0d590.png)
:
