### ISSUE TITLE
Heron no longer spawning

### ISSUE THREAD

**Issue by jacksonhshields** [heron/heron_simulator#2]
Hi,
The Heron is no longer spawning within UUV simulator, perhaps due to the recent changes with UUV Simulator. These are the errors that I'm getting when trying to run heron_world.launch:

[Err] [Plugin.hh:165] Failed to load plugin libunderwater_object_ros_plugin.so: libunderwater_object_ros_plugin.so: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:165] Failed to load plugin libthruster_ros_plugin.so: libthruster_ros_plugin.so: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:165] Failed to load plugin libthruster_ros_plugin.so: libthruster_ros_plugin.so: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:165] Failed to load plugin libjoint_state_publisher.so: libjoint_state_publisher.so: cannot open shared object file: No such file or directory

**Comment by tonybaltovski** [comment]
Hi,

This was fixed here: https://github.com/heron/heron/pull/7.
