### ISSUE TITLE
Error running heron_world.launch

### ISSUE THREAD

**Issue by djmv** [heron/heron_simulator#20]
- OS: Ubuntu 18.04
 - ROS Distro: Melodic
 - Built from source or installed: Installed by apt

 **Expected behaviour**
I installed heron simulator following instructions in [https://www.clearpathrobotics.com/assets/guides/melodic/heron/simulation.html](url) then I tried to run `heron_world.launch` but said me that teleop.launch not found.  
 
**Actual behaviour**
```RLException:` while processing /src/heron_simulator/heron_gazebo/launch/spawn_heron.launch:
while processing /opt/ros/melodic/share/heron_control/launch/teleop.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/opt/ros/melodic/share/heron_control/launch/teleop.launch'
The traceback for the exception was written to the log file```

**Other notes**
Also I installed all teleop packages by apt but the error was not solved. `sudo apt install ros-melodic-teleop-*`
All the packages: 
```ros-melodic-teleop-legged-robots ros-melodic-teleop-tools-msgs ros-melodic-teleop-twist-joy-dbgsym ros-melodic-teleop-tools ros-melodic-teleop-twist-joy ros-melodic-teleop-twist-keyboard```

**Comment by civerachb-cpr** [comment]
Please try cloning the latest version of https://github.com/heron/heron into your workspace; there was a recent update that added teleop.launch to the heron_control package that may not be available as a .deb yet.

**Comment by djmv** [comment]
Thanks! @civerachb-cpr I solved the issue. I copied into `heron_simulator` folder the `heron_control` folder from https://github.com/heron/heron Then I did `catkin_make` and relaunch the `heron_world` and run successfully.
