### ISSUE TITLE
heron_gazebo depends on uuv_simulator but, it is not given as dependency

### ISSUE THREAD

**Issue by ozzdemir** [heron/heron_simulator#21]
**Please provide the following information:**
 - OS: Ubuntu 18.04
 - ROS Distro: Melodic
 - Built from source
 - Package version: a086c053d5defe8ad286616549f8af943833d73a

 **Expected behaviour**
Rosdep install command to install all depending packages
`rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y`

 **Actual behaviour**
 Additional packages are required for `roslaunch heron_gazebo heron_world.launch` to work properly, such as uuv_assistants and more.

**To Reproduce**
Provide the steps to reproduce:
1. run something
2. launch something else
3. see the error

**Other notes**
Adding uuv_simulator as run_dependency resulted in expected_behaviour.

**Comment by civerachb-cpr** [comment]
Thanks for letting us know about this issue!
