### ISSUE TITLE
Camera for kinetic package

### ISSUE THREAD

**Issue by PhilipAmadasun** [heron/heron_simulator#23]
**Describe the the feature you would like**
I am not sure, but I don't believe there is an option to implement camera sensors for the simulator(for kinetic package). If there is, or if there is a way to add that, where should I look?

**Other notes**
Add anything else you thing is important.

**Comment by tonybaltovski** [comment]
Hi Philip, you can add this yourself as done here: https://github.com/jackal/jackal/blob/kinetic-devel/jackal_description/urdf/accessories.urdf.xacro#L51

Good luck!
