### ISSUE TITLE
Implementation on ROS 2

### ISSUE THREAD

**Issue by sontung1010** [heron/heron_simulator#24]
Hello, I am trying to implement the Heron model simulator on ROS 2. Can you let me know what the function of uuv_simulator in this project is? Do I need the uuv_simulator if I only intend to use the 3D model only? Thank you very much.

**Comment by civerachb-cpr** [comment]
Clearpath Robotics stopped supporting the Heron after ROS Melodic. We have no current plans to release any ROS 2 packages for Heron.

The UUV Simulator was used to supply the water surface physics for the simulation.  I don't know what the current state of ROS 2 water simulation is, but if you don't need the physics simulation for your application then you can probably skip that dependency.

**Comment by tonybaltovski** [comment]
Also, if you just need a model, the URDF should be all you need: https://github.com/heron/heron/tree/melodic-devel/heron_description

**Comment by sontung1010** [comment]
Ok thank you very much
